# The matrix elements of angular momentum

1. Build the function `j_mat` that takes as input the variable $j$, and returns the matrix elements of angular momentum in quantum mechanics

$$(J^2)_{a,b} = j(j+1) \delta_{a,b}$$
$$(J_z)_{a,b} = m(b,j) \delta_{a,b}$$ 
$$(J_+)_{a,b} = \sqrt{j(j+1)-m(b,j)[m(b,j)+1]} \delta_{a,b+1}$$ 
$$(J_-)_{a,b} = \sqrt{j(j+1)-m(b,j)[m(b,j)-1]} \delta_{a,b-1}$$ 

where $a$ and $b$ are integer numbers in $[0,2 j]$ (both 0 and $2 j$ are included), and we have defined $m(b,j)=b-j$.

The delta function has the following definition
$\delta_{a,b} = 1$ if $a=b$; $\delta_{a,b} = 0$ if $a\neq b$.

Print the four matrices $J^2$, $J_z$, $J_+$ and $J_-$ for $j = 1$ and for $j = 1/2$.

In [1]:
import numpy as np

In [2]:
def m(b,j):
    return b-j


def j_mat(j):
    ndim = int(2*j+1)
    J2 = np.zeros((ndim,ndim),dtype='f8')
    Jz = np.zeros((ndim,ndim),dtype='f8')
    Jp = np.zeros((ndim,ndim),dtype='f8')
    Jm = np.zeros((ndim,ndim),dtype='f8')
    #
    for a in range(ndim):
        for b in range(ndim):
            if a == b :
                J2[a,b]=j*(j+1)
                Jz[a,b]=m(b,j)
            if a == b+1 : 
                Jp[a,b]=np.sqrt(j*(j+1)-m(b,j)*(m(b,j)+1))
            if a == b-1 : 
                Jm[a,b]=np.sqrt(j*(j+1)-m(b,j)*(m(b,j)-1))

    return J2, Jz, Jp, Jm

In [3]:
for j in [1,0.5]:
    J2, Jz, Jp, Jm = j_mat(j)
    print(f"j  = {j}")
    print(f"J^2 = \n{J2}")
    print(f"J_z = \n{Jz}")
    print(f"J_+ = \n{Jp}")
    print(f"J_- = \n{Jm}")
    print(" ")

j  = 1
J^2 = 
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
J_z = 
[[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]
J_+ = 
[[0.         0.         0.        ]
 [1.41421356 0.         0.        ]
 [0.         1.41421356 0.        ]]
J_- = 
[[0.         1.41421356 0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
 
j  = 0.5
J^2 = 
[[0.75 0.  ]
 [0.   0.75]]
J_z = 
[[-0.5  0. ]
 [ 0.   0.5]]
J_+ = 
[[0. 0.]
 [1. 0.]]
J_- = 
[[0. 1.]
 [0. 0.]]
 


### 2. For all values of j = $1/2, 1, 3/2, 2, 5/2, 3$ verify the following commutation relations
$$[J_x,J_y]=iJ_z$$ 
$$[J_z,J_x]=iJ_y$$ 
$$[J_y,J_z]=iJ_x$$ 
$$[J_z,J_+]=J_+$$ 
$$[J_z,J_-]=-J_-$$ 
$$[J_+,J_-]=2J_z$$ 
$$[J^2,J_z]=0$$ 
$$[J^2,J_+]=0$$ 
$$[J^2,J_-]=0$$ 
where $J_x=\frac{J_+ + J_-}{2}$, $J_y=\frac{J_+ - J_-}{2i}$, and $i$ is the imaginary unit. 
The commutator between $A$ and $B$ is defined as the following matrix product:
$[A,B]=A B - B A$.

In [2]:
#### YOUR CODE HERE ####




########################

3. Build the follwing matrices 
$$ S^2 = J^2(j=1/2) \otimes I(3) $$
$$ S_z = J_z(j=1/2) \otimes I(3) $$
$$ S_+ = J_+(j=1/2) \otimes I(3) $$
$$ S_- = J_-(j=1/2) \otimes I(3) $$
$$ S_x = (S_+ + S_-)/2 $$
$$ S_y = (S_+ - S_-)/(2i) $$
$$ L^2 = I(2) \otimes J^2(j=1) $$
$$ L_z = I(2) \otimes J_z(j=1) $$
$$ L_+ = I(2) \otimes J_+(j=1) $$
$$ L_- = I(2) \otimes J_-(j=1) $$
$$ L_x = (L_+ + L_-)/2 $$
$$ L_y = (L_+ - L_-)/(2i) $$
$$ K_x = S_x + L_x $$
$$ K_y = S_y + L_y $$
$$ K_z = S_z + L_z $$
$$ K^2 = K_xK_x + K_yK_y + K_zK_z $$

The Kronecker product between two matrices, i.e. $A \otimes B$, can be evaluated with the numpy function `kron(A,B)`. The identity matrix of size $n$, i.e. $I(n)$, can be evaluated using the numpy function `eye(n)`.

In [5]:
J2, Jz, Jp, Jm = j_mat(0.5)
S2 = np.kron(J2,np.eye(3))
Sz = np.kron(Jz,np.eye(3))
Sp = np.kron(Jp,np.eye(3))
Sm = np.kron(Jm,np.eye(3))
Sx = (Sp+Sm)/2
Sy = (Sp-Sm)/2j
J2, Jz, Jp, Jm = j_mat(1)
L2 = np.kron(np.eye(2),J2)
Lz = np.kron(np.eye(2),Jz)
Lp = np.kron(np.eye(2),Jp)
Lm = np.kron(np.eye(2),Jm)
Lx = (Lp+Lm)/2
Ly = (Lp-Lm)/2j
Kx = Sx + Lx
Ky = Sy + Ly
Kz = Sz + Lz
K2 = Kx@Kx + Ky@Ky + Kz@Kz

### 4. Verify that $K^2$, $K_z$, $S^2$, $L^2$ is a set of commuting matrices, i.e. that $[A,B]=0$ for any matrix $A$ and matrix $B$ in the set.

In [1]:
#### YOUR CODE HERE ####




########################